vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") then vim.cmd("syntax reset") end
vim.g.colors_name = "mono"
vim.o.background = "dark"

local p = {
    bg      = "#0a0a0a",
    bg1     = "#111111",
    bg2     = "#18181b",
    bg3     = "#27272a",
    bg4     = "#3f3f46",
    mid     = "#52525b",
    dim     = "#71717a",
    muted   = "#a1a1aa",
    subtle  = "#d4d4d8",
    text    = "#e4e4e7",
    bright  = "#fafafa",
    none    = "NONE",
}

local function hi(name, opts)
    vim.api.nvim_set_hl(0, name, opts)
end

-- Editor
hi("Normal",          { fg = p.text,   bg = p.bg })
hi("NormalNC",        { fg = p.muted,  bg = p.bg })
hi("NormalFloat",     { fg = p.text,   bg = p.bg1 })
hi("FloatBorder",     { fg = p.bg3,    bg = p.bg1 })
hi("ColorColumn",     { bg = p.bg1 })
hi("Conceal",         { fg = p.bg4 })
hi("Cursor",          { fg = p.bg,     bg = p.text })
hi("CursorIM",        { fg = p.bg,     bg = p.text })
hi("CursorLine",      { bg = p.bg1 })
hi("CursorLineNr",    { fg = p.muted,  bold = true })
hi("CursorColumn",    { bg = p.bg1 })
hi("Directory",       { fg = p.text })
hi("EndOfBuffer",     { fg = p.bg2 })
hi("ErrorMsg",        { fg = p.text,   bold = true })
hi("VertSplit",        { fg = p.bg3,   bg = p.bg })
hi("WinSeparator",    { fg = p.bg3,    bg = p.bg })
hi("Folded",          { fg = p.dim,    bg = p.bg1 })
hi("FoldColumn",      { fg = p.bg4,    bg = p.bg })
hi("SignColumn",      { fg = p.bg4,    bg = p.bg })
hi("IncSearch",       { fg = p.bg,     bg = p.muted })
hi("Search",          { fg = p.bg,     bg = p.dim })
hi("CurSearch",       { fg = p.bg,     bg = p.text })
hi("LineNr",          { fg = p.bg4 })
hi("MatchParen",      { fg = p.bright, underline = true })
hi("ModeMsg",         { fg = p.dim })
hi("MoreMsg",         { fg = p.dim })
hi("NonText",         { fg = p.bg3 })
hi("Pmenu",           { fg = p.text,   bg = p.bg1 })
hi("PmenuSel",        { fg = p.bg,     bg = p.muted })
hi("PmenuSbar",       { bg = p.bg2 })
hi("PmenuThumb",      { bg = p.bg4 })
hi("Question",        { fg = p.muted })
hi("QuickFixLine",    { bg = p.bg2 })
hi("SpecialKey",      { fg = p.bg4 })
hi("SpellBad",        { undercurl = true })
hi("SpellCap",        { undercurl = true })
hi("SpellLocal",      { undercurl = true })
hi("SpellRare",       { undercurl = true })
hi("StatusLine",      { fg = p.dim,    bg = p.bg1 })
hi("StatusLineNC",    { fg = p.bg4,    bg = p.bg })
hi("Substitute",      { fg = p.bg,     bg = p.dim })
hi("TabLine",         { fg = p.dim,    bg = p.bg1 })
hi("TabLineFill",     { fg = p.bg4,    bg = p.bg })
hi("TabLineSel",      { fg = p.text,   bg = p.bg2, bold = true })
hi("Title",           { fg = p.text,   bold = true })
hi("Visual",          { bg = p.bg3 })
hi("VisualNOS",       { bg = p.bg3 })
hi("WarningMsg",      { fg = p.muted })
hi("Whitespace",      { fg = p.bg3 })
hi("WildMenu",        { fg = p.bg,     bg = p.muted })

-- Syntax — apenas bold/italic para diferenciar, sem cor
hi("Comment",         { fg = p.bg4,    italic = true })
hi("Constant",        { fg = p.subtle })
hi("String",          { fg = p.muted })
hi("Character",       { fg = p.muted })
hi("Number",          { fg = p.subtle })
hi("Boolean",         { fg = p.subtle, bold = true })
hi("Float",           { fg = p.subtle })
hi("Identifier",      { fg = p.text })
hi("Function",        { fg = p.text,   bold = true })
hi("Statement",       { fg = p.muted,  bold = true })
hi("Conditional",     { fg = p.muted,  bold = true })
hi("Repeat",          { fg = p.muted,  bold = true })
hi("Label",           { fg = p.muted })
hi("Operator",        { fg = p.dim })
hi("Keyword",         { fg = p.muted,  bold = true })
hi("Exception",       { fg = p.muted,  bold = true })
hi("PreProc",         { fg = p.dim })
hi("Include",         { fg = p.dim })
hi("Define",          { fg = p.dim })
hi("Macro",           { fg = p.dim })
hi("PreCondit",       { fg = p.dim })
hi("Type",            { fg = p.subtle, bold = true })
hi("StorageClass",    { fg = p.subtle, bold = true })
hi("Structure",       { fg = p.subtle, bold = true })
hi("Typedef",         { fg = p.subtle, bold = true })
hi("Special",         { fg = p.dim })
hi("SpecialChar",     { fg = p.dim })
hi("Tag",             { fg = p.dim })
hi("Delimiter",       { fg = p.bg4 })
hi("SpecialComment",  { fg = p.bg4,    italic = true })
hi("Debug",           { fg = p.muted })
hi("Underlined",      { underline = true })
hi("Error",           { fg = p.text,   bold = true, underline = true })
hi("Todo",            { fg = p.bright, bold = true })

-- Diff
hi("DiffAdd",         { bg = p.bg2 })
hi("DiffChange",      { bg = p.bg1 })
hi("DiffDelete",      { fg = p.bg4,    bg = p.bg1 })
hi("DiffText",        { bg = p.bg3 })
hi("Added",           { fg = p.subtle })
hi("Changed",         { fg = p.dim })
hi("Removed",         { fg = p.mid })

-- Treesitter
hi("@comment",               { link = "Comment" })
hi("@string",                { link = "String" })
hi("@number",                { link = "Number" })
hi("@boolean",               { link = "Boolean" })
hi("@keyword",               { link = "Keyword" })
hi("@keyword.function",      { fg = p.muted, bold = true })
hi("@keyword.return",        { fg = p.muted, bold = true })
hi("@function",              { link = "Function" })
hi("@function.builtin",      { fg = p.subtle, bold = true })
hi("@function.call",         { fg = p.text })
hi("@method",                { fg = p.text,  bold = true })
hi("@method.call",           { fg = p.text })
hi("@variable",              { fg = p.text })
hi("@variable.builtin",      { fg = p.muted })
hi("@parameter",             { fg = p.text,  italic = true })
hi("@property",              { fg = p.subtle })
hi("@field",                 { fg = p.subtle })
hi("@type",                  { link = "Type" })
hi("@type.builtin",          { fg = p.subtle, bold = true })
hi("@namespace",             { fg = p.dim })
hi("@constructor",           { fg = p.text,  bold = true })
hi("@operator",              { link = "Operator" })
hi("@punctuation.delimiter", { fg = p.bg4 })
hi("@punctuation.bracket",   { fg = p.mid })
hi("@tag",                   { fg = p.muted, bold = true })
hi("@tag.attribute",         { fg = p.dim })
hi("@tag.delimiter",         { fg = p.bg4 })
hi("@text",                  { fg = p.text })
hi("@text.title",            { fg = p.text,  bold = true })
hi("@text.emphasis",         { italic = true })
hi("@text.strong",           { bold = true })
hi("@text.uri",              { fg = p.dim,   underline = true })
hi("@constant",              { link = "Constant" })
hi("@constant.builtin",      { fg = p.subtle, bold = true })

-- LSP
hi("DiagnosticError",           { fg = p.muted })
hi("DiagnosticWarn",            { fg = p.dim })
hi("DiagnosticInfo",            { fg = p.bg4 })
hi("DiagnosticHint",            { fg = p.bg4 })
hi("DiagnosticUnderlineError",  { underline = true })
hi("DiagnosticUnderlineWarn",   { underline = true })
hi("DiagnosticUnderlineInfo",   { })
hi("DiagnosticUnderlineHint",   { })

-- Telescope / fzf
hi("TelescopeNormal",         { fg = p.text,  bg = p.bg1 })
hi("TelescopeBorder",         { fg = p.bg3,   bg = p.bg1 })
hi("TelescopeSelection",      { bg = p.bg2 })
hi("TelescopeSelectionCaret", { fg = p.muted, bg = p.bg2 })
hi("TelescopeMatching",       { fg = p.bright, bold = true })
hi("TelescopePromptNormal",   { fg = p.text,  bg = p.bg2 })
hi("TelescopePromptBorder",   { fg = p.bg3,   bg = p.bg2 })

-- GitSigns
hi("GitSignsAdd",    { fg = p.bg4 })
hi("GitSignsChange", { fg = p.bg4 })
hi("GitSignsDelete", { fg = p.bg4 })
